---
title: "Mosaic Integration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Mosaic Integration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MosaicNMF)
```

```{r data}
set.seed(123)
K27 <- Matrix(sample(0:1, 50, replace=TRUE), nrow=10, sparse=TRUE)
CUTAC <- Matrix(sample(0:1, 50, replace=TRUE), nrow=10, sparse=TRUE)
K4 <- Matrix(sample(0:1, 50, replace=TRUE), nrow=10, sparse=TRUE)

# Assign cell names (column names)
colnames(K27) <- c("Cell1", "Cell2", "Cell3", "Cell4", "Cell5")
colnames(CUTAC) <- c("Cell2", "Cell3", "Cell6", "Cell7", "Cell8")
colnames(K4) <- c("Cell3", "Cell4", "Cell7", "Cell9", "Cell10")

rownames(K27) = paste0("K27_",1:10)
rownames(K4) = paste0("K4_",1:10)
rownames(CUTAC) = paste0("CUTAC_",1:10)
```

```{r}
testList = c(K27,CUTAC,K4)

a_mat = stackMatrix(dataList = testList)
getRandomMask(dataList = testList,ratio = .20,seed = 2)
plotMSEvsRank(dataset = a_mat,ranks = 1:10,mask="NA",seed = 123)
#validateImputedValues()
```

