# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rand_spmat <- function(nrow, ncol, inv_density, seed) {
    .Call('_MosaicNMF_rand_spmat', PACKAGE = 'MosaicNMF', nrow, ncol, inv_density, seed)
}

rand_mat <- function(nrow, ncol, seed) {
    .Call('_MosaicNMF_rand_mat', PACKAGE = 'MosaicNMF', nrow, ncol, seed)
}

c_nmf <- function(A, tol, maxit, verbose, L1, w) {
    .Call('_MosaicNMF_c_nmf', PACKAGE = 'MosaicNMF', A, tol, maxit, verbose, L1, w)
}

c_nmf_rand <- function(seed, nrow, ncol, k, maxit) {
    .Call('_MosaicNMF_c_nmf_rand', PACKAGE = 'MosaicNMF', seed, nrow, ncol, k, maxit)
}

#' Automatic benchmarking using random matrices
#' 
#' @export
run_benchmarking <- function() {
    .Call('_MosaicNMF_run_benchmarking', PACKAGE = 'MosaicNMF')
}

getMaskVector <- function(ind, dim, rows, cols, dimSize) {
    .Call('_MosaicNMF_getMaskVector', PACKAGE = 'MosaicNMF', ind, dim, rows, cols, dimSize)
}

